---
title: NHSRdatasets
author: ''
date: '2019-10-06'
slug: NHSRdatasets
categories:
  - R
tags:
  - R
  - package
draft: false
summary: NHSRdatasets - a collaborative datasets package for teach and learning R in healthcare contexts
image:
  caption: ''
  focal_point: ''
output:
  blogdown::html_page:
    toc: true
    number_sections: true
    toc_depth: 1
---

# NHSRdatasets - v0.2.0 

This package has been created to help NHS, Public Health and related analysts/data scientists learn to use R. It contains several free datasets (just one at the moment), help files explaining their structure, and vignette examples of their use. We encourage contributions to the package, both to expand the set of training material, but also as development for newer R/github users as a first contribution. Please add relevant free, open source data sets that you think may benefit the NHS R-community.

The package was created for, and on behalf of, the NHS-R Community:  https://nhsrcommunity.com/

__v0.1.1__  Initial version of the package contained a single simulated dataset based on minimal hospital 'spell' type table with demographics, length-of-stay, and whether patients died.  Designed for teaching regression methods, this dataset is a useful example in many areas.

__v0.1.2__ Second release of the package added data from NHS A&E datasets, prepared by @tomjemmet, from NHS England data.

__v0.2.0__ Third release of the package reorganised and cleaned the package with better compression, converted data to tibble formats, and addition of the ONS mortality dataset, prepared by @Lextuga007.

For more information, see:

- CRAN: https://cran.r-project.org/web/packages/NHSRdatasets/index.html
- Package Site: https://nhs-r-community.github.io/NHSRdatasets/
- GitHub: https://github.com/nhs-r-community/NHSRdatasets


